#%Module1.0

set compilernames [regexp -all -inline {\S+} [regsub -all {/\S*} "ROLLCOMPILER" ""]]

module-whatis "hdf4"
module-whatis "Version: VERSION"
module-whatis "Description: hdf4"
module-whatis "Compiler: $compilernames"

# Figure out the applicable compiler--either the one whose module was loaded
# when this modulefile was loaded or the one with the most-recently-loaded
# module.  Report an error if neither applies.
if [info exists env(HDF4HOME)] {
  foreach {compiler} $compilernames {
    if {[string first "/$compiler" $::env(HDF4HOME)] >= 0} {
      break
    }
  }
} elseif [info exists env(LOADEDMODULES)] {
  foreach {module} [split $::env(LOADEDMODULES) :] {
    set module [lindex [split $module /] 0]
    if {[regexp [format {%s(/|\s|$)} $module] $compilernames]} {
      set compiler $module
    }
  }
}
if { ! [info exists compiler] } {
  puts stderr "Need to load a compiler module first"
  exit 1
}

set hdf4Home /opt/hdf4/$compiler
setenv HDF4HOME $hdf4Home
prepend-path PATH $hdf4Home/bin
prepend-path LD_LIBRARY_PATH $hdf4Home/lib
prepend-path LIBPATH $hdf4Home/lib
