#%Module1.0
module-whatis "hdf5"
module-whatis "Version: VERSION"
module-whatis "Description: hdf5"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
# Look for MPI flavor in LOADEDMODULES. If no MPI module is loaded, default to
# first element in ROLLMPI.
set mpi [lindex [split "ROLLMPI" "/ "] 0]
foreach {module} [split $::env(LOADEDMODULES) :] {
  set module [lindex [split $module /] 0]
  if {[regexp [format {%s(/|\s|$)} $module] "ROLLMPI"]} {
    set mpi $module
  }
}
set hdf5Home /opt/hdf5/COMPILERNAME/$mpi
setenv HDF5HOME $hdf5Home
prepend-path PATH $hdf5Home/bin
prepend-path LD_LIBRARY_PATH $hdf5Home/lib
prepend-path LIBPATH $hdf5Home/lib
set lib [glob -nocomplain $hdf5Home/lib/python*/site-packages]
prepend-path PYTHONPATH $lib
