#%Module1.0
module-whatis "hdf5"
module-whatis "Version: VERSION"
module-whatis "Description: hdf5"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
if {! [info exists ::env(MPIHOME)] || ! [info exists ::env(LOADEDMODULES)]} {
  puts stderr "Need to load an mpi module before loading fftw/VERSION"
  exit 1
}
foreach {x} [list ROLLMPI] {
  # Look for flavor in LOADEDMODULES, delimited by colon or end of string.
  # Can also be followed by / (version number).
  if {[regexp [format {(:|^)%s([:/]|$)} $x] $::env(LOADEDMODULES)]} {
    set mpi $x
    break
  }
}
if {! [info exists mpi]} {
  puts stderr "No supported MPI flavor found"
  exit 1
}
set hdf5Home /opt/hdf5/COMPILERNAME/$mpi
setenv HDF5HOME $hdf5Home
prepend-path PATH $hdf5Home/bin
prepend-path LD_LIBRARY_PATH $hdf5Home/lib
prepend-path LIBPATH $hdf5Home/lib
set lib [glob -nocomplain $hdf5Home/lib/python*/site-packages]
prepend-path PYTHONPATH $lib
