#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
module-whatis	 hdf4 
module-whatis	 Version: VERSION 
module-whatis	 Description: hdf4 
module-whatis	 Compiler: ROLLCOMPILER 
setenv		 HDF4HOME /opt/hdf4/ROLLCOMPILER 
prepend-path	 PATH /opt/hdf4/ROLLCOMPILER/bin 
prepend-path	 LD_LIBRARY_PATH /opt/hdf4/ROLLCOMPILER/lib 
prepend-path	 LIBPATH /opt/hdf4/ROLLCOMPILER/lib 
END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; /bin/ln -s .version.VERSION .version )
